pring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springbootdata?\
     characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
  jpa:
    show-sql: true